name: S3 upload pipeline

on:
    workflow_call:

    workflow_dispatch:

defaults:
  run:
    working-directory: ./consumer
    
jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws_key }}
          aws-secret-access-key: ${{ secrets.aws_sec_key }}
          aws-region: 'eu-central-1'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run consumer
        env:
          kafka_bootstrap_server: ${{ secrets.KAFKA_BOOTSTRAP_SERVER }}
          sasl_username: ${{ secrets.SASL_USERNAME }}
          sasl_password: ${{ secrets.SASL_PASSWORD }}
        run: python consumer.py

      - name: Run DBT Transformations
        uses: ./github/workflows/dbt.yml