name: S3 upload pipeline

on:
  workflow_call:
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      kafka_bootstrap_server:
        required: true
      sasl_username:
        required: true
      sasl_password:
        required: true
      SNOWFLAKE_ACCOUNT:
        required: true
      SNOWFLAKE_USER:
        required: true
      SNOWFLAKE_PASSWORD:
        required: true
      SNOWFLAKE_ROLE:
        required: true
      SNOWFLAKE_DATABASE:
        required: true
      SNOWFLAKE_WAREHOUSE:
        required: true
      SNOWFLAKE_SCHEMA:
        required: true

  workflow_dispatch:


defaults:
  run:
    working-directory: ./consumer

jobs:
  run-s3-upload-pipeline:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.aws_key }}
        aws-secret-access-key: ${{ secrets.aws_sec_key }}
        aws-region: 'eu-central-1'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run consumer
      env:
        kafka_bootstrap_server: ${{ secrets.KAFKA_BOOTSTRAP_SERVER }}
        sasl_username: ${{ secrets.SASL_USERNAME }}
        sasl_password: ${{ secrets.SASL_PASSWORD }}
      run: python consumer.py

  dbt-pipeline:
    needs: run-s3-upload-pipeline
    uses: ./.github/workflows/dbt.yaml
    secrets:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
